### ISSUE TITLE
PowerShell window

### ISSUE THREAD

**Issue by tapochek666** [limbo666/Dublicate_RightClick#1]
Everything works fine, but how do I hide the PowerShell window that appears and disappears?

**Comment by limbo666** [comment]
Unfortutatelly there is no easy way to do this... the script launch must be changed to be launched by an extrernal source and in that case there is a issue with system permisions.
I would love to find a solution for that but for the moment I have no solution to offer. 😯

**Comment by tapochek666** [comment]
Thanks for the answer. It's a pity (

вт, 3 дек. 2024 г. в 22:45, limbo666 ***@***.***>:
